### ISSUE TITLE
Trigger site deployment from Diligent Engine repo

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentGraphics.github.io#1]
Pack WebAsm artifacts in actions when main repository is built.

```
# .github/workflows/dispatch.yml in the source repository
name: Dispatch Event

on:
  push:
    branches:
      - main  # or the branch you want to track

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/<target_owner>/<target_repo>/dispatches
          token: ${{ secrets.GITHUB_TOKEN }}
          body: '{"event_type": "custom_event"}'
```

```
# .github/workflows/on-dispatch.yml in the target repository
name: On Dispatch

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add other steps you want to perform here
```
